PRODUCT_VERSION_MAJOR = 14
PRODUCT_VERSION_MINOR = 0

LINEAGE_BUILD_DATE := $(shell date +%Y%m%d)

# Set LINEAGE_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef LINEAGE_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "LINEAGE_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^LINEAGE_||g')
        LINEAGE_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE OFFICIAL TEST,$(LINEAGE_BUILDTYPE)),)
    LINEAGE_BUILDTYPE := UNOFFICIAL
    DISPLAY_BUILDTYPE := Unofficial
else ifeq ($(LINEAGE_BUILDTYPE), TEST)
    LINEAGE_BUILDTYPE := TEST
    DISPLAY_BUILDTYPE := Test
else
    LINEAGE_BUILDTYPE := OFFICIAL
    DISPLAY_BUILDTYPE := Official
endif

LINEAGE_PRODUCT_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)
LINEAGE_VERSION_SUFFIX := $(LINEAGE_PRODUCT_VERSION)-$(DISPLAY_BUILDTYPE)-$(LINEAGE_BUILD_DATE)

# Internal version
LINEAGE_VERSION := Altair-$(LINEAGE_VERSION_SUFFIX)-$(LINEAGE_BUILD)

# Display version
LINEAGE_DISPLAY_VERSION := $(LINEAGE_VERSION_SUFFIX)
